### PR TITLE
Bump eth-hash version

### PR DESCRIPTION
**Pull request by dylanjw**
### What was wrong?

web3.py requires eth-hash version >0.2.0 and eth-bloom <0.2.0

### How was it fixed?
Bump version ceiling in setup.py

#### Cute Animal Picture

image

### CODE REVIEW

**Review by carver — APPROVED** [review]

**Comment by carver** [comment]
Technically it should be a major version bump to drop support for python version 3.4, but... it has been broken for 5 months and no one noticed. So yeah I guess we can just drop it.

**Comment by dylanjw** [comment]
This PR now includes dropping python 3.4 support.

**Comment by carver** [comment]
Should drop 3.4 from the setup.py file, too:

```
'Programming Language :: Python :: 3.4',
```

**Comment by carver** [comment]
3.4 is still listed in setup.py

**Pull request merged**
